-- =====================================================
-- VagaMonitor - Schema V1
-- Compativel com H2 e PostgreSQL
-- =====================================================

CREATE TABLE IF NOT EXISTS criterios_busca (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    palavra_chave     VARCHAR(256) NOT NULL,
    localizacao       VARCHAR(256),
    total_resultados  INT,
    buscado_em        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vagas (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo       VARCHAR(512) NOT NULL,
    empresa      VARCHAR(256),
    localizacao  VARCHAR(256),
    url_original VARCHAR(1024) NOT NULL,
    id_externo   VARCHAR(512) UNIQUE,
    descricao    VARCHAR(2000),
    fonte        VARCHAR(64),
    criado_em    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Índice para busca por identificador externo (deduplicação)
CREATE INDEX IF NOT EXISTS idx_vagas_id_externo ON vagas(id_externo);
